### PR TITLE
Update projects to .NET sdk, support `netstandard2.0`, drop tfms, etc

### LINKED ISSUE #21: Cross-platform build, maybe with Paket+FAKE?
Since I have some free time right now, I've been trying to test out the `digit-separator` branch as requested in https://github.com/stephan-tolksdorf/fparsec/issues/2#issuecomment-284523607, but I only have a Linux development machine, so PowerShell build scripts aren't all that easy for me to use. Result: the Windows-only build process for FParsec is currently blocking me from making any progress on helping with #2.

Would you be interested in a cross-platform build process, using Paket and FAKE instead of NuGet and PowerShell? I can't guarantee that I'd have time to work on it anytime soon, but I would be willing to put in the work if you'd find it useful — and if I can find the time (always the biggest limiting factor for me). I just don't want to invest the time in making a cross-platform build process if you wouldn't find that useful.

### LINKED ISSUE #34: Assembly version mismatch, caused by netstandard1.6 support
Support for netstandard1.6 causes assembly binding trouble, at least when support for netstandard2.0 would be preferred.

Steps to reproduce
===
Suppose you have two F# (or C#) projects, namely a library `libfoo` and an application `appbar`. libfoo targets netstandard2.0, and appbar targets .NET Framework 4.7.2.

Also, suppose libfoo uses FParsec.  In particular, libfoo depends upon the ``FParsec`` NuGet package, version 1.0.4-RC3.  Also, libfoo must reference FParsec types, even if in a trivial way, to cause libfoo to load the FParsec assemblies.

A suitable example libfoo.fs follows:

```fsharp
module libfoo =
    let p : FParsec.Primitives.Parser<unit, unit> = Unchecked.defaultof<_>
    let nonConst () : int =
        System.Environment.MachineName.Length
```

Finally, suppose appbar depends upon libfoo.  In particular, appbar must load libfoo, by calling into libfoo.nonConst().  The last being non-constant is important; otherwise the compiler could optimize away the loading of the libfoo assembly.

Expected result
===
appbar calls libfoo.nonConst, and successfully receives a return value.

Actual result
===
appbar calling libfoo.nonConst causes an exception:

```FileLoadException: Could not load file or assembly 'FParsecCS, Version=1.0.4.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)```

Environment
===
I am using recent Visual Studio 2017 (v15.8.7), and NuGet (v4.8.1).

Non-causes and non-fixes
===
Many things can be changed or added, and still trigger this bug:
- Adding missing (or removing) AutoGenerateBindingRedirects to appbar's project file (.csproj or .fsproj) does not make this problem go away.
- Changing FParsec.dll and FParsecCS.dll's AssemblyVersion doesn't help.  Whilst FParsec's AssemblyFileVersion/FileVersion is set as expected to e.g. ``1.0.4.0``, the AssemblyVersion tends to be set to ```1.0.0.0```.  This surprised me.  Regardless, changing AssemblyVersion to match AssemblyFileVersion/FileVersion does not solve the bug.
- downgrading libfoo's netstandard version to 1.6 doesn't help
- downgrading appbar's .NET Framework version to 4.7.1 doesn't help
- switching either or both of libfoo and appbar's languages, to C# from F#, doesn't help
- switching libfoo and appbar's project files (.csproj or .fsproj) between the "old style" (e.g. VS2015), and the modern style (MSBuild Project SDK) doesn't help

Also, this issue affects every version of FParsec with netstandard1.6 support, namely from 1.0.3 beta upwards.

Also, FWIW, I needed two projects, the libfoo and appbar: I could not reproduce the issue with only one project.

Workarounds
===
Now, this issue can be avoided by changing libfoo to target .NET Framework (e.g. v4.7.2), or changing appbar to target netcoreapp (v1.0, v1.1, v2.0 or v2.1).  Unfortunately, this is not always feasible.

The above fact suggests to me that this could be a bug in the .NET Framework's support of netstandard.

Nonetheless, it may be easier and faster to work around this issue in FParsec.  In particular, the issue can be fixed if FParsec targets netstandard2.0 instead of netstandard1.6.  Weirdly, and in support of my supposition this is a .NET Framework bug, it is not enough for FParsec to target netstandard2.0 in addition to netstandard1.6

Next steps
===
Would you be willing to target netstandard2.0 instead of netstandard1.6?  And if so, would you prefer a pull request, or to implement the change yourself?

Moreover, please ping me if you have trouble building an unmodified FParsec with the recent version of Visual Studio I am using. In particular, as a separate issue, there are some changes which might be required to the way FSharp.Core is referenced.

### PR DESCRIPTION
**Pull request by enricosada**
create a modern package, use .net sdk, cleanup infra, add ci.

## Supported frameworks

add support for `netstandard2.0`

drop support for discontinued `net40-client` target framework.
it's not used anymore in .NET >= 4.5
ref https://docs.microsoft.com/en-us/dotnet/framework/deployment/client-profile

drop support for `netstandard1.6`, it's useful only in .NET Core v1.
replaced by `netstandard2.0`

drop support for `.NETPortable`( `portable-net45+win8+wp8+wpa81` ) target framework.
the PCL profiles are replaced by .NET Standard.
- the compiler defines `PCL` is not used anymore. The code is not yet removed
  because it's a big change, but because the compiler define is not set, the
  code is unused

## Dependencies

pin `FSharp.Core` to be >= v4.3.4 for all target framework to simplify deps

## Projects

add `global.json` to pin .net core sdk version to make build deterministic

upgrade form FSharp.NET.Sdk style (deprecated in .NET Core Sdk 1.0) to .NET Sdk fsproj

cleanup shared props and fsproj, using conventions of .NET Sdk:

- refactor common properties in an automatically imported `Directory.Build.props`
- move props near usage in projects
- remove now useless FParsec.Samples.Common.targets
- upgrade tests from netcoreapp2.0 to netcoreapp2.1

remove old VS11 projects, new projects works in VS

## Build script

update `pack.psi` powershell script, to use `dotnet` commands instead of msbuild/nuget
nupkgs are generated in `~/bin/nupkg`

## CI

Add appveyor:
- run `pack.ps1`
- version suffix autogenerated by buildId/branch/PR. no suffix if is a tag (so just tag to generate a stable version)
- generated nupkgs are in the artifacts tab of appveyor, ready to download

Add travis:
- osx/ubuntu
- run `dotnet build` on both `Release` and `Release-LowTrust` configurations
- run tests only if `netcoreapp`. It can run also `net45` test using mono but i am too lazy to write the if in the travis script (but the matrix is there)

## Issues

fix #34 (support `netstandard` and `net` tfms)
fix #21 (just run `dotnet` commands, but replacing the powershell is easy too)

### CODE REVIEW

**Comment by enricosada** [comment]
I'll also add appveyor/travis to this PR, to check works ok in win/unix/osx.

but afaik is ok

**Comment by enricosada** [comment]
appveyor ok ( https://ci.appveyor.com/project/enricosada/fparsec/builds/22526608/artifacts )

**Comment by enricosada** [comment]
travis ok ( https://travis-ci.org/enricosada/fparsec/builds/496199497 )

**Comment by enricosada** [comment]
@stephan-tolksdorf 	ready to review.

feel free to enable the travis and appveyor in the main repo after the merge.

**Comment by stephan-tolksdorf** [comment]
Thank you for working on updating the project files and update script, @enricosada!

I'll start review the PR in the coming days.

It would be great if the project files worked as best as possible in VS 2019. (Making them work in VS 2017 might not be worth the effort due to bugs like https://github.com/dotnet/project-system/issues/2733)

Switching the configuration, e.g. from Debug to Debug-LowTrust, currently doesn't seem to work properly in VS 2019 Preview 3 with the new project files from this PR. Maybe @cartermp knows whether this is a fundamental limitation of VS's project system or something that we could fix.

**Comment by enricosada** [comment]
i updated the sln.
Now both conf are avaiable in configuration manager and the switch of configuration rebuild the correct dll.

When i switch conf, the compiler defines change, but not intellisense like your linked bug

image

@stephan-tolksdorf can you try with VS 2019? i have only VS 2017 installed.

I think another issue in VS 2017 is that we use conditional target frameworks (`net45` vs `net45+netstandard2.0`). i get wierd bugs like:

image

I'll try to minimize a repro and send a bug to `visualfsharp`/`dotnet/project-system`, but maybe is ok in VS2019

**Comment by cartermp** [comment]
There shouldn't be any changes needed to make the project files work with VS 2019. The underlying system is the same; it's just that VS 2019 now has more bug fixes and perf improvements that won't be backported to VS 2017.

**Comment by stephan-tolksdorf** [comment]
VS 2019 still has the bug with the duplicate properties sheets. 

The editor in VS 2019 updates the syntax highlighting of C# code when switching the configuration, but this doesn't seem to work (yet?) for F# code.

IntelliJ Rider doesn't seem to have such issues.

@enricosada Did you check that the net45 DLLs are codesigned and have the expected version information?

What's the current best practice with regard to packaging symbols/supporting stepping through code during debugging? (There's another PR open by @ctaggart adding source link support.)

**Comment by ctaggart** [comment]
>What's the current best practice with regard to packaging symbols/supporting stepping through code during debugging?

> If you distribute the library via a package published to NuGet.org, it is recommended to build a symbol package and publish it to NuGet.org as well. This will make the symbols available on NuGet.org symbol server, where the debugger can download it from when needed. Alternatively, you can include the symbols in the main package. However, doing so is not recommended as it increases the size of the package and thus restore time for projects that consume your package.
https://github.com/dotnet/sourcelink

**Comment by enricosada** [comment]
Best practice is sourcelink because awesome. 

I’ll send a PR later with that

**Comment by enricosada** [comment]
I think are strong signed, but i’ll double check.
Maybe we can string sign also netstandard because less maintenance (one if less)

**Comment by stephan-tolksdorf** [comment]
I'd prefer to only sign the .Net framework assemblies, until there's a clear need to also sign the netstandard ones. (Shipping signed assemblies is a decision that can't be reverted without potentially breaking downstream projects.)

**Comment by enricosada** [comment]
Sure.

meanwhile i think i can split the fsprojs in two, to avoid the need for two configution.
Will simplify the usage i think

**Comment by buybackoff** [comment]
> I'd prefer to only sign the .Net framework assemblies, until there's a clear need to also sign the netstandard ones. (Shipping signed assemblies is a decision that can't be reverted without potentially breaking downstream projects.)

Signed assemblies do not create any problems for unsigned consumers, but unsigned ones are impossible to consume from signed ones. Clear need is when a netstandard assembly A is consumed by another netstandard assembly B which also targets .NET classic and netcore, and the B assembly is consumed by a .NET classic assembly C that is signed. If A (FParsec is this case) is not signed then B cannot be signed and C cannot consume it. Please make all assemblies signed and commit the key to the repo. I believe this is de facto a standard for open projects (e.g. Dapper, Nodatime).

> Maybe we can string sign also netstandard because less maintenance (one if less)

Signed is much easier to maintain not only than than two but also then unsigned - you do it once, forget about it and never get issues/complaints that some signed assembly cannot use yours.

**Comment by enricosada** [comment]
I'd like to not enter the discussion about strong naming here, because is always really long. Just to be clear, for me is a big no.

What matter is that the fparsec net45 is strong signed, that's ok and must continue to be like that (it's out of scope for this PR).

I checked the built assemblies and are strong signed

```
>sn -vf lib\net45\FParsecCS.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Assembly 'lib\net45\FParsecCS.dll' is valid
```

@stephan-tolksdorf as a note, i tried in https://github.com/enricosada/fparsec/tree/split_prop to split the LowTrust in multiple fsproj (so FParsec.fsproj and `FParsec.BigData.fsproj`) to remove the need for multiple configurations.
But dunno, was not worth it, because we trade some issues for others.

So for me this PR is ready

- appveyor ✔️  ( https://ci.appveyor.com/project/enricosada/fparsec/builds/22703797 ), note that the built nupkg are in [artifacts tab](https://ci.appveyor.com/project/enricosada/fparsec/builds/22703797/artifacts)
- travis ✔️  ( https://travis-ci.org/enricosada/fparsec/builds/499532477 )

**Comment by cartermp** [comment]
Any discussion about strong naming should involve Paket vs. NuGet, Tabs vs. Spaces, and Vim vs. Emacs 😄

**Comment by buybackoff** [comment]
Frankly I'm surprised that there is strong opinion not to sign. Not once I
had to build myself (Deedle, Math.NET, older Dapper), and wonder if there
is a single person out there who had to rebuild a signed assembly as
non-signed because signed is unusable. What inconvenience one line in a
project file could cause?

You are forcing to multitarget when classic framework signed final consumer
is involved.

But with practice forking+repacking becomes not so difficult. Much easier
than such discussions.

**Comment by stephan-tolksdorf** [comment]
@enricosada Thanks again for your work on this PR! I'm going to review it this weekend so that we can merge it.

I'm curious, why did you switch to conditionals based on TargetFramework from TargetFrameworkIdentifier in 63f5049 (after deleting the fallback initialization of TargetFrameworkIdentifier in 5231fbd)?

**Comment by enricosada** [comment]
Because the strong sign wasn’t enabled.

that property TargetFrameworkIdentity is set from a taarget later than the conditional evaluation, so was evaluated to false.

**Comment by stephan-tolksdorf** [comment]
> that property TargetFrameworkIdentity is set from a taarget later than the conditional evaluation, so was evaluated to false.

I think that's why I originally set the `TargetFrameworkIdentifier` manually when it was empty in `FParsec.Common.targets` (before 5231fbd), but I'm fine with just using `TargetFramework` directly instead.

 Do you still want to add the SourceLink support?

**Comment by enricosada** [comment]
Yes, i’ll add sourcelink later in another PR
This one is already big enough

**Comment by stephan-tolksdorf** [comment]
Great work @enricosada! I think this PR is ready to be merged.

I've made some minor adjustments. Let me know if you find any of them objectionable.

If you think the PR is ready, please squash the PR, give it a descriptive commit message and then rebase merge it with master. (I've invited you as a GitHub contributor.)

Thank you so much for your contribution!

**Comment by enricosada** [comment]
Done, thanks @stephan-tolksdorf

**Comment by rmunn** [comment]
As the one who reported #21, I'm happy to see that someone tackled this. Thanks @enricosada!

**Comment by enricosada** [comment]
ref https://github.com/stephan-tolksdorf/fparsec/issues/39 to track sourcelink

**Comment by cartermp** [comment]
Great work @enricosada

**Comment by btrepp** [comment]
Is it possible to get this released as another RC?. Currently have issues with mixing netframework and netstandard libs.

**Pull request merged**
