### PR TITLE
Building FParsec for .NET Core

### PR DESCRIPTION
**Pull request by neoeinstein**
This begins the process of making FParsec build on .NET Core. There are some significant changes that may merit a full version bump.

* No longer building a Profile259 version. Building for portable and .NET Core is a pain, and future "portable" libraries should target .NET Standard.
* The low trust version builds to `FParsec`, while the full trust version builds to `FParsec.FullTrust`. The underlying DLL is still `FParsec.dll` for both.
* .NET 4.5 is the only target for the full trust version due to needed APIs missing from .NET Core
* `FParsec` and `FParsecCS` are distributed as separate packaged in line with the new .NET NuGet model.

`FParsec` and `FParsecCS` target `net45` and `netstandard1.6`
`FParsec.FullTrust` and `FParsecCS.FullTrust` target `net45`

To build, follow the steps in the `appveyor.yml` file or run `build.ps1`.

On an extra note, I think it would be a good idea to turn the existing samples into benchmarks using BenchmarkDotNet.

Status of the build can be found here: https://ci.appveyor.com/project/neoeinstein/fparsec

### CODE REVIEW

**Comment by stephan-tolksdorf** [comment]
Thanks for working on this!

Let me quickly summarize here what we discussed by email:

- I think it's important that we (continue to) support Visual Studio 2015 & 2017. Ideally we could use the same solution file, but if that's too complicated, we can just keep separate ones as before. 

- A problem with the F# support in VS 2017 RC 4 seems to prevent the solution file in your PR from loading. Hopefully this will fixed in the final release on Tuesday, though  https://github.com/Microsoft/visualfsharp/issues/2362#issuecomment-281420209 seems to suggest that it might take some time.

- The /nooptimizationdata fsc compiler flag for the F# dll seems to have been lost in the conversion. Adding it back may also make the new `NoInlining` annotations unnecessary.

**Comment by cloudRoutine** [comment]
To deal with the lack of VS support I've been generating the netcore fsproj with each build so that they stay synchronized with any changes to my old style fsproj

https://github.com/fsharp-editing/FSharp.Editing/tree/master/scripts

**Comment by neoeinstein** [comment]
To @stephan-tolksdorf's notes:

* VS 2017 wants to update the solution file. VS 2015 can't read the updated solution file. This is unfortunate, but should also be noted that support for VS 2015's .NET Core extension support stopped at `project.json`, and won't be updated to support the new `msbuild`. Thus I think we leave VS 2015 behind and focus on VS 2017 and VSCode.

  My goal is to be able to have a user open VS 2017 or VSCode and press `Ctrl+Shift+B` and have a working build (in addition to `dotnet build` from the command line).

* I am still having trouble with getting things to open properly in VS 2017. I will update my VS 2017 to use the "nightly" version of the Visual F# Tools extension and see if that helps.

* Which is preferrable? Disabling optimization data in whole for the F# compiler, or just ensuring that these couple of methods don't get improperly inlined? I think that by attributing the couple of functions, we can let the F# compiler continue to make better optimization decisions, but here I don't quite know what other uses the optimization data has.

**Comment by neoeinstein** [comment]
So, it appears that VS 2017 still won't support .NET Core projects for a while. I can create some pseudo-projects, though, which will allow opening and viewing the project from VS 2017. Is that your preference?

**Comment by stephan-tolksdorf** [comment]
The solution in the VS11 folder (that you removed) seems to work fine in VS 2017, so I think we should keep it around for a little longer (with updated configuration options if necessary), or would that be a big problem? Once a VS release with working F# .NET Core support is out, we can jettison the old solution. Also, if the new solution doesn't yet work with Visual Studio, we should document that prominently.

Regarding the /nooptimizationdata flag: Is there any clear rule for where we have to apply the NoInlining attribute? When I originally added the flag I was under the impression that there wasn't really an alternative. We did use that flag previously, so it keeping it wouldn't be a performance regression (though I don't think that it makes a big difference anyway, because the optimizations by  the F# compiler are rather limited and the JIT does its own inlining).

**Comment by cloudRoutine** [comment]
If you set the heading of the sln to 
```

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 14
VisualStudioVersion = 14.0.25420.1
MinimumVisualStudioVersion = 10.0.40219.1
```
it should work fine in all the versions and vs2017 won't try to upgrade it when it opens

**Comment by neoeinstein** [comment]
For the `/nooptimizationdata` flag, I'm going to tag @dsyme and link to the places in the code where I used the `NoInlining` attribute:
https://github.com/stephan-tolksdorf/fparsec/pull/5/files#diff-f36aef5143648626001ad997e2c89589

I have re-added the VS 2011 and VS 2014 files.

**Comment by dsyme** [comment]
> The /nooptimizationdata fsc compiler flag for the F# dll seems to have been lost in the conversion. Adding it back may also make the new NoInlining annotations unnecessary.

My recommendation would be to just never use ``/nooptimizationdata``.  It's never needed in these days of nuget packages and frequent binary recompilation

**Comment by stephan-tolksdorf** [comment]
@dsyme The reason I [originally added /nooptimizationdata](https://bitbucket.org/fparsec/main/issues/16/fparsec-needs-nooptimizationdata-to-avoid) is that the F# compiler sometimes inlines functions without properly checking that the inlined body only accesses public parts of the API. This problem continues to exist. We can avoid the resulting `MethodAccessException`s  by adding `MethodImplAttribute(MethodImplOptions.NoInlining)` to the erroneously inlined F# functions, which suppresses inlining both by fsc and the JIT. However, it's not clear to me how we can be sure exactly which functions need that attribute applied. I assume this depends at least in part on the inlining heuristic used by (a specific version of) the F# compiler.

**Comment by stephan-tolksdorf** [comment]
@cloudRoutine Thank you for suggesting to change the file header. I didn't get very far by playing with the header, but I think @neoeinstein had more success. I'm not sure how flexible the C# & F# project support in Visual Studio is (or will be) with regard to the MSBuild features used in the project files. I suspect that we eventually might have to make some compromises if we want full IDE support in VS.

**Comment by baronfel** [comment]
A strategy that other projects have been using is to have a dedicated maintain both old MSBuild project and solution files (that is, the full-framework build) and a smaller set of netcore solution and project files.  Build and package these as well (using simple `dotnet restore`, `dotnet build`, and `dotnet pack` commands, then use the `mergenupkg` tool to merge the netcore nugets into the full-framework nugets as a unified package, then distribute that.

That lets you still work on the core code in VS2015/2017 while also providing a netcore build.  You can look at https://github.com/fsharp/FSharp.Compiler.Service as an example.  If this sounds useful I'd be glad to do that work.

**Comment by stephan-tolksdorf** [comment]
@baronfel Thanks for your offer to help! I'd like to consolidate on the new build system as much as possible. Currently the main problem is that we can't get the strong naming to work for the netstandard assemblies.

**Comment by stephan-tolksdorf** [comment]
@neoeinstein, Thank you again for your work on this PR! 

I've made some changes in follow-up commits. In particular, the Low-Trust and non-Low-Trust editions are now built using the same project files with the help of different project configurations. I've also added PCL 259 support (for package backwards compatibility), worked around the missing generation of assembly attributes for F# and tricked the msbuild Pack task into including the FParsecCS files in the FParsec NuGet package.

If you have the time, I'd appreciate if you could maybe take a quick look at the changes I made to see if there's something obviously wrong. If you or anyone else has any question, I'd be happy to explain the modifications I made.

It seems that InternalsVisibleTo is not properly supported on NET Core for strong-named assemblies. I'm pretty sure I saw an issue acknowledging that somewhere on GitHub, but I'm having difficulties finding it again.  Anyway, since there is no backward compatibility restriction, I think it's better just to not strong name the new netstandard assemblies.

I'll push out new pre-release NuGet packages later today.

**Pull request merged**
